* Atelier "Décode ta richesse avec la blockchain Cardano"
Ce dossier contient des ressources pour 5 jours d'ateliers organisés par WADACI.  Vous y trouverez les images, les notes de cours, les exercices et les diapositives utilisé pendant ces 5 journées.

** Notes techniques
- Les sources des présentations sont au format org-mode de [[https://www.gnu.org/software/emacs/][GNU emacs]].  Si vous n'en avez pas entendu parlé regardez la très bonne vidéo de System crafters "[[https://www.youtube.com/watch?v=PNE-mgkZ6HM&t=1s][Emacs From Scratch #6 - Organisez votre vie avec le mode Org]]".

  J'utilise ensuite `org-beamer-export-to-latex` pour convertir le `.org` en `.tex`  et je compile le `LaTeX` pour obtenir des fichiers pdf présentables.

  Les pages de garde sont faites avec [[https://inkscape.org/fr/][inkscape]].

  
* Remerciements
  Cet atelier n'aurait pas pu se faire sans le concours du [[https://cncci.edu.ci/][Centre de calcul de Côte d'ivoire]] et la générosité de son directeur:   Doc. Issa Traoré.
  Nous avons aussi reçu un soutient financier de la part de la [[https://wada.org][West African Decentralized Alliance]].  Puisse-t-ils recevoir en retour notre infinie gratitude.

[[file:impact.org][ref. inpact report]]
