 Activité pratique de la deuxième journée de l'atelier.
 
** Créer une blockchain en python à partir de zéro
 - Objectif : 
Créer une application qui permet à ses utilisateurs de publier des messages sur une blockchain en utilisant une interface simple.
 - Prérequis :
Avoir une environnement de développement python installé.
Etre capable de comprendre et d'executer des commandes linux dans windows.

** Prérequis installation de l'IDE

*** télécharger et installer un éditeur de texte

*** Installer python 3.8.4 (ou une version plus récente)

https://www.python.org/downloads/windows/

(Pour windows) Cocher la case "add python" to PATH au moment de l'installation
**** Vérifier que python est bien installé
- Ouvrir un terminal (ou invite de commande) et taper

#+BEGIN_SRC bash  
python --version
#+END_SRC

*** Créer l'arborescence du projet

#+BEGIN_SRC bash  -i
projet_blockchain
└── blockchain_tuto
#+END_SRC

Pour créer un dossier projet_blockchain et un sous-dossier blockchain_tuto, saisir dans un terminal:
#+BEGIN_SRC bash  -i
mkdir projet_blockchain ; cd projet_blockchain; mkdir blockchain_tuto
pip install virtualenv
virtualenv .
Scripts\activate

# pour afficher le contenu du dossier
dir 
#+END_SRC

*** Créer l'environnement virtuel

Pour installer des programmes (ou des bibliothèques) python utilisons le gestionnaire de paquet officiel python qui s'appelle 'pip'

Commençons par installer un programme qui va gérer notre environnement
#+BEGIN_SRC bash  -i
pip install virtualenv
#+END_SRC

puis créons l'environnement virtuel
#+BEGIN_SRC bash  -i
virtualenv .
#+END_SRC
le '.' indique le dossier courant

Cela crée les dossiers 'Scripts' et 'Lib' et isole notre projet des autres projets python que vous pourrions développer par ailleur.

Activons cet environnement à la racine du projet (dans le dossier projet_blockchain)
#+BEGIN_SRC bash  -i
Scripts\activate
# parfois il faut faire Scripts\activate.bat
#+END_SRC

Une fois l'environnement activité vous devriez voir le nom du dossier aparaitre entre parenthèse.

Pour désactiver l'environnement virutel faites
#+BEGIN_SRC bash  -i
Scripts\deactivate
#+END_SRC
 
** Étapes  (programmation)

Dans le dossier blockchain_tuto
#+BEGIN_SRC bash  -i
projet_blockchain
└── blockchain_tuto
#+END_SRC

Créer le fichier 'noeud_serveur.py' (avec sublime texte, par exemple)

*** Enregistrer les transactions dans des blocs

Chaque transaction doit contenir:
- un contenu
- un auteur
- une étiquette temporelle

Stockons tout ça dans une structure `json` comme suit:
#+begin_json
{
"author": "non d'auteur",
"content": "quelque chose dit par l'auteur",
"timestamp": "le temps de la publication"
}
#+end_json

Dans le fichier `noeud_serveur.py` créer la class block
#+begin_src python  -i
class block:
    def __init__(self, index, transactions, timestamp):
        self.index = index 
        self.transactions = transactions 
        self.timestamp = timestamp

#+end_src

*** Ajouter une empreinte digitale sur les blocs

+################ pause jusqu'à 11h  ################+

 Pour s'assurer qu'il n'y a pas modification du bloc nous utilisons une fonction cryptographique, le hash.  Cette fonction a les propriétés suivantes:
 - Facile à calculer,
 - Pour une entrée donnée, elle renvoie toujours la même chose en sortie (le hash).
 - Le resultat paraît uniformement aléatoire.

Grâce à ces propriétés, il est impossible de retrouver les données originelles en connaissant le hash.  Parcontre, il est facile de vérifier qu'un hash correspond à une entrée particulière.

Pour créer le hash du text 'test' en python, nous utilisons
 #+begin_src python  -i
from hashlib import sha256
sha256(b'test').hexdigest()
 #+end_src

Nous sauvegardons le hash du bloc dans un champ de l'objet bloc (voir plus haut la `class block`).  Ce hash est comme la carte d'identité du block.

 #+begin_src python  -i
from hashlib import sha256
import json

def calculer_hash(block):
    bloc_string = json.dumps(self.__dict__, sort_keys=true)
    return sha256(block_string.encode()).hexdigest()
 #+end_src

En pratique chaque transactions est hashée individuellement. Dans notre cas, nous simplifions notre code en hashant toutes les transactions d'un seul coup, mais  cela ne change pas le fonctionnement de la blockchain.

*** Enchainer les blocs

Maintenant que nous avons des blocks, il nous faut les lier.  Nous pourrions simplement utiliser une liste python.  Cependant, quelqu'un pourrait remplacer un ancien bloc par un nouveau bloc dans la liste sans que cela se voit immédiatement.

Pour nous assurer que le changement d'un bloc invalide toute la chaine de bloc nous créons une dépendance entre les blocs en les enchainant les un les autres avec leur hash.  C'est à dire que chaque nouveau bloc contient le hash du bloc précédent.

Se pose alors la question du premier bloc.  Il s'appelle le bloc de génèse (genesis block, car il est particulier. C'est le seul qui n'inclut pas le hash d'un autre bloc.

Ajoutons, donc, un champ /prec_hachage/ à notre objet bloc et nous implémentons la structure initiale de la blockchain

 #+begin_src python  -i
from hashlib import sha256
import json
import time


class bloc:
    def __init__(self, index, transactions, timestamp, prec_hachage, nonce=0):
        self.index = index
        self.transactions = transactions
        self.timestamp = timestamp
        self.prec_hachage = prec_hachage
        self.nonce = nonce

    def calcule_hachage(self):
        """retourne la hachage du contenu du bloc."""
        bloc_string = json.dumps(self.__dict__, sort_keys=true)
        return sha256(bloc_string.encode()).hexdigest()


class chainedeblocs:
    # difficulte de notre algorithme de preuve
    difficulte = 2

    def __init__(self):
        self.tx_non_confirmees = []
        self.chaine = []

    def creer_bloc_genese(self):
        """
        Crée le bloc génèse et l'ajoute à notre chaine.
        ce bloc à une index 0, un prec_hachage null et un hachage valide
        """
        bloc_genese = bloc(0, [], 0, "0")
        bloc_genese.hachage = bloc_genese.calcule_hachage()
        self.chaine.append(bloc_genese)

    @property
    def dernier_bloc(self):
        return self.chaine[-1]
 #+end_src

Dorénavant, si le contenu d'un bloc change:
 - son hash change
 - son hash ne correspond plus à celui référencé dans le bloc suivant
 - le hash du bloc suivant change et ainsi de suite.  Aussi, en vérifiant le hash du dernier bloc savons automatiquement si cette chaine de blocs est identique à une autre chaine dont nous vérifions le dernier block uniquement.

*** Implémenter l'algorithm de preuve par le travail

Cependant, il y reste un problème.  Il est simple de changer un bloc et de recalculer son hash ainsi que celui de tous les autres bloc pour former une nouvelle chaine valide. Si deux chaines diffèrent, comment savoir laquelle contient les informations juste.
La solution est de rendre le calcul du hash difficile, en  acceptant uniquement les hash qui commencent par un nombre prédéfini de zéros.  Par exemple, si c'est 3,  le hash d'un bloc doit être de la forme '000abdefhash...'

Cependant la forme du hash dépend des données, et nous ne voulons pas les changer.
La solution est d'ajouter un petit quelque chose en plus des données.  C'est le *nonce* (numerical once).  C'est un nombre que aléatoire que nous trouvons en essayant successivement, de façon incrémentale, de calculer le hash pour qu'il ait la forme voulu.

Dans la blockchain cette technique s'appelle l'algorithm du *Hashcash*.  Nous en implémentons une version simplifiée.  Le nombre de zéro va définir la difficulté de la preuve par le travail.  Plus il y aura de zéros plus ce sera difficle de trouver le bon *nonce*.  Par contre se sera toujours aussi facile de vérifier que le hash est correct.

#+BEGIN_SRC python  -i
class Chainedeblocs:
# ...
    @staticmethod
    def preuve_du_travail(bloc):
        """
        Essaye differentes valeurs pour le nonce afin d'avoir un hachage
        qui satisfait le critère de difficulté.
        """
        bloc.nonce = 0

        hachage = bloc.calcule_hachage()
        while not hachage.startswith("0" * Chainedeblocs.difficulte):
            bloc.nonce += 1
            hachage = bloc.calcule_hachage()

        return hachage
#+END_SRC

Remarque: il n'y a pas de stratégie particulière pour trouver le nonce. Il faut tout tester, ou utiliser du matériel qui peut calculer des hash avec moins d'instructions CPU.

*** Ajouter un bloc sur la chaine

Pour ajouter un bloc à la chaine nous devons d'abord vérifier que:
- le bloc est valide (ie. par la preuve du travail, le nonce, doit être correcte)
- l'ordre des transactions est préservés, le prec_hachage doit correspondre au hash du dernier bloc dans notre chaine

#+BEGIN_SRC python  -i
class Blockchain:
    # ...

    def add_block(self, block, proof):
        prec_hachage = self.last_block.hash

        if prec_hachage != block.prec_hachage:
            return False

        if not Blockchain.is_valid_proof(block, proof):
            return False

        block.hash = proof
        self.chain.append(block)
        return True

    def is_valid_proof(self, block, block_hash):
        return (block_hash.startswith('0' * Blockchain.difficulty) and
                block_hash == block.compute_hash())
#+END_SRC

**** Miner les transations

Au départ les transactions ne sont pas confirmées et elles attendent d'être incluses dans un bloc.
Les mettre dans un bloc et calculer le hash (preuve par le travail), c'est  /miner/ un bloc.  Une fois le bloc miné, nous l'ajoutons à la chaine.

Dans la plus part des cryptmonaies, les mineurs reçoivent une récompense pour leur travail.  Inclure cette fonctionnalité est un exercice pour ceux qui veulent aller plus loin.

#+BEGIN_SRC python  -i
class Blockchain:

    def __init__(self):
        self.unconfirmed_transactions = [] # data yet to get into blockchain
        self.chain = []
        self.create_genesis_block()

    """
    Previous code contd...
    """

    def add_new_transaction(self, transaction):
        self.unconfirmed_transactions.append(transaction)

    def mine(self):
        if not self.unconfirmed_transactions:
            return False

        last_bloc = self.last_block

        new_bloc = Block(index=last_block.index + 1,
                          transactions=self.unconfirmed_transactions,
                          timestamp=time.time(),
                          prec_hachage=last_block.hash)

        proof = self.proof_of_work(new_block)
        self.add_block(new_block, proof)
        self.unconfirmed_transactions = []
        return new_block.index
#+END_SRC

*** Créer les interfaces

On va utiliser `Flask` un micro-framework pour créer l'API REST qui va interagir et invoquer nos différentes opérations sur le noeud de la blockchain.
- Installer 'flask' avec *pip install flask* ainsique *pip install requests*
- Puis ajouter le code suivant ua fichier principal

#+BEGIN_SRC python  -i
from flask import Flask, request
import requests

# Initialize flask application
app =  Flask(__name__)

# Initialize a blockchain object.
blockchain = Blockchain()
#+END_SRC

Ajoutons de nouvelles transactions avec le code suivant

#+BEGIN_SRC python  -i
# Flask's way of declaring end-points
@app.route('/new_transaction', methods=['POST'])
def new_transaction():
    tx_data = request.get_json()
    required_fields = ["author", "content"]

    for field in required_fields:
        if not tx_data.get(field):
            return "Invalid transaction data", 404

    tx_data["timestamp"] = time.time()

    blockchain.add_new_transaction(tx_data)

    return "Success", 201
#+END_SRC

Voici un autre point d'entrée pour récupérer la copie de la chaine détenue par le noeud interrogé.

#+BEGIN_SRC python  -i
@app.route('/chain', methods=['GET'])
def get_chain():
    chain_data = []
    for bloc in blockchain.chain:
        chain_data.append(block.__dict__)
    return json.dumps({"length": len(chain_data),
                       "chain": chain_data})
#+END_SRC

Ci-dessous, nous demandons au noeud de miner les transactions non confirmées, si il y en a:
#+BEGIN_SRC python  -i
@app.route('/mine', methods=['GET'])
def mine_unconfirmed_transactions():
    result = blockchain.mine()
    if not result:
        return "No transactions to mine"
    return "Block #{} is mined.".format(result)

@app.route('/pending_tx')
def get_pending_tx():
    return json.dumps(blockchain.unconfirmed_transactions)
#+END_SRC

*** Etablir le consensus et la décentralisation

Jusqu'à maintenant la blockchain est implémentée pour tourner sur un seul ordinateur. Cependant, nous voulons que les données soient distribués car nous ne pouvons avoir confiance en une seule machine.

Pour gérer la décentralisation un noeud d'être au courant de l'existance des autres noeuds. Implémentons ce méchanisme.

#+BEGIN_SRC python  -i
# Contains the host addresses of other participating members of the network
peers = set()

# Endpoint to add new peers to the network
@app.route('/register_node', methods=['POST'])
def register_new_peers():
    # The host address to the peer node 
    node_address = request.get_json()["node_address"]
    if not node_address:
        return "Invalid data", 400

    # Add the node to the peer list
    peers.add(node_address)

    # Return the blockchain to the newly registered node so that it can sync
    return get_chain()


@app.route('/register_with', methods=['POST'])
def register_with_existing_node():
    node_address = request.get_json()["node_address"]
    if not node_address:
        return "Invalid data", 400

    data = {"node_address": request.host_url}
    headers = {'Content-Type': "application/json"}

    # Make a request to register with remote node and obtain information
    response = requests.post(node_address + "/register_node",
                             data=json.dumps(data), headers=headers)

    if response.status_code == 200:
        global blockchain
        global peers
        # update chain and the peers
        chain_dump = response.json()['chain']
        blockchain = create_chain_from_dump(chain_dump)
        peers.update(response.json()['peers'])
        return "Registration successful", 200
    else:
        # if something goes wrong, pass it on to the API response
        return response.content, response.status_code


def create_chain_from_dump(chain_dump):
    blockchain = Blockchain()
    for idx, block_data in enumerate(chain_dump):
        bloc = Block(block_data["index"],
                      block_data["transactions"],
                      block_data["timestamp"],
                      block_data["prec_hachage"])
        proof = block_data['hash']
        if idx > 0:
            added = blockchain.add_block(block, proof)
            if not added:
                raise Exception("The chain dump is tampered!!")
        else:  # the bloc is a genesis block, no verification needed
            blockchain.chain.append(block)
    return blockchain
#+END_SRC

Créons ensuite le mécanisme pour informer les autres noeud (ordinateur) que nous avons miné un bloc. Ainsi chaque noeud peut mettre à jour sa chaine et miner les autres transactions.  Les autres noeuds vérifient aussi, que la preuve du travail (le nonce) est correct avant d'ajouter le bloc à leur chaine.

#+BEGIN_SRC python  -i
# endpoint to add a bloc mined by someone else to
# the node's chain. The node first verifies the block
# and then adds it to the chain.
@app.route('/add_block', methods=['POST'])
def verify_and_add_block():
    block_data = request.get_json()
    bloc = Block(block_data["index"],
                  block_data["transactions"],
                  block_data["timestamp"],
                  block_data["prec_hachage"])

    proof = block_data['hash']
    added = blockchain.add_block(block, proof)

    if not added:
        return "The bloc was discarded by the node", 400

    return "Block added to the chain", 201


def announce_new_block(block):
    for peer in peers:
        url = "{}add_block".format(peer)
        requests.post(url, data=json.dumps(block.__dict__, sort_keys=True))
#+END_SRC

Nous appelons "announce_new_block" à chaque nouveau bloc miné pour que les autres noeud mettent à jour leur chaine.

#+BEGIN_SRC python  -i
@app.route('/mine', methods=['GET'])
def mine_unconfirmed_transactions():
    result = blockchain.mine()
    if not result:
        return "No transactions to mine"
    else:
        # Making sure we have the longest chain before announcing to the network
        chain_length = len(blockchain.chain)
        consensus()
        if chain_length == len(blockchain.chain):
            # announce the recently mined bloc to the network
            announce_new_block(blockchain.last_block)
        return "Block #{} is mined.".format(blockchain.last_block.index
#+END_SRC

*** Monter l'application
 Le serveur de blockchain est prêt.  Il reste à finir l'interface de l'application.

Nous avons besoin de connecter le noeud au réseau des blockchains pour récupérer et soumettre les données.  

La fonction 'fetch_posts' va récupérer les données du point d'entrée '/chain', l'analyser et le stocker localement.
Nous écrivons cela dans app/views.py

 #+BEGIN_SRC python  -i
import datetime
import json

import requests
from flask import render_template, redirect, request

from app import app

# Node in the blockchain network that our application will communicate with
# to fetch and add data.
CONNECTED_NODE_ADDRESS = "http://127.0.0.1:8000"

posts = []
 #+END_SRC


 #+BEGIN_SRC python  -i
def fetch_posts():
    get_chain_address = "{}/chain".format(CONNECTED_NODE_ADDRESS)
    response = requests.get(get_chain_address)
    if response.status_code == 200:
        content = []
        chain = json.loads(response.content)
        for bloc in chain["chain"]:
            for tx in block["transactions"]:
                tx["index"] = block["index"]
                tx["hash"] = block["prec_hachage"]
                content.append(tx)

        global posts
        posts = sorted(content,
                       key=lambda k: k['timestamp'],
                       reverse=True)
 #+END_SRC

Notre application a un formulaire html pour effectuer des requêt POST vers un noeud connecté et ajouter des transactions dans la /memepool/.  Les transactions sont ensuite minées par le réseau et nous les récupérons en rafraichissant la page

 #+BEGIN_SRC python  -i
@app.route('/submit', methods=['POST'])
def submit_textarea():
    """
    Endpoint to create a new transaction via our application
    """
    post_content = request.form["content"]
    author = request.form["author"]

    post_object = {
        'author': author,
        'content': post_content,
    }

    # Submit a transaction
    new_tx_address = "{}/new_transaction".format(CONNECTED_NODE_ADDRESS)

    requests.post(new_tx_address,
                  json=post_object,
                  headers={'Content-type': 'application/json'})

    # Return to the homepage
    return redirect('/')
 #+END_SRC

*** Lancer l'application
Démarrer le serveur
#+BEGIN_SRC bash  -i
$ export FLASK_APP=node_server.py
$ flask run --port 8000
#+END_SRC

dans un autre terminal lancer l'application
#+BEGIN_SRC bash  -i
$ python run_app.py
#+END_SRC

Le programme devrait tourner sur http:://localhost:5000
**** Plusieurs noeuds
Nous pouvons enregsitrer plusieurs noeud en faisant sur une même machine 
#+BEGIN_SRC bash  -i
# already running
$ flask run --port 8000 &
# spinning up new nodes
$ flask run --port 8001 &
$ flask run --port 8002 &
#+END_SRC

et
#+BEGIN_SRC bash  -i
$ curl -X POST \
  http://127.0.0.1:8001/register_with \
  -H 'Content-Type: application/json' \
  -d '{"node_address": "http://127.0.0.1:8000"}'

$ curl -X POST \
  http://127.0.0.1:8002/register_with \
  -H 'Content-Type: application/json' \
  -d '{"node_address": "http://127.0.0.1:8000"}'
#+END_SRC

Les nouveaux noeuds sur les port 8001 et 8002 se synchroniseront.

Pour mettre à jour le noeud avec lequel l'application se synchronise (localhost port 8000) il faut changer CONNECTED_NODE_ADDRESS dans views.py

Une fois tout ça fait, nous pouvons lancer l'application avec
#+BEGIN_SRC bash  -i
python run_app.py
#+END_SRC
Créer de nouvelles transactions (publier des messages via l'interface web)
quand nous minons des transaction,  tous les noeuds du réseau mettent à jour leur chaine.  Nous pouvons vérifier les chaines en regardant /chain avec curl
#+BEGIN_SRC bash  -i
$ curl -X GET http://localhost:8001/chain
$ curl -X GET http://localhost:8002/chain
#+END_SRC

*** Authentification
Il y a un problème dans notre application.  N'importe qui peut publier n'importe quoi.  Donc il faut un mecanisme pour authentifier les transactions.  C'est là qu'interviennent les pairs de clefs public/privée.

- Chaque transaction doit être signé (avec la clef privé) et cette signature est ajouté au message ainsi que la clef publique.
- Pendant la vérification, on vérifie que celui qui dit avoir écrit la transaction (clef public) est bien celui qui a signé.

*** la suite
Essayer à plusieurs en utilisant [[https://www.ngrok.com/][ngrok]] pour créer une adresse publique à partir de on server local
